AWSTemplateFormatVersion: 2010-09-09
Description: Aurora MySQL cluster.
Parameters:
  DatabaseName:
    Default: "kayoAurora"
    Description: The database name (Default "aurora", change if you are creating more than one database)
    Type: String

  DBInstanceClass:
    #https://docs.amazonaws.cn/en_us/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Managing.Performance.html
    Type: String
    Default: db.t2.medium
    AllowedValues:
    - db.m1.small
    - db.m1.medium
    - db.m1.large
    - db.m1.xlarge
    - db.m2.xlarge
    - db.m2.2xlarge
    - db.m2.4xlarge
    - db.m3.medium
    - db.m3.large
    - db.m3.xlarge
    - db.m3.2xlarge
    - db.m4.large
    - db.m4.xlarge
    - db.m4.2xlarge
    - db.m4.4xlarge
    - db.m4.10xlarge
    - db.r3.large
    - db.r3.xlarge
    - db.r3.2xlarge
    - db.r3.4xlarge
    - db.r3.8xlarge
    - db.t2.micro
    - db.t2.small
    - db.t2.medium
    - db.t2.large

  DatabasePassword:
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must contain only alphanumeric characters. Must have length 8-41.
    Description: The database admin account password. (Choose a secure password)
    MaxLength: '41'
    MinLength: '8'
    NoEcho: 'true'
    Type: String

  DatabaseUsername:
    Default: "aurora"
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must contain only alphanumeric characters. Must have length 1-16
    Description: The database admin account user name. (Default "aurora")
    MaxLength: '16'
    MinLength: '1'
    Type: String

  AllocatedStorage:
    Default: 20
    Description: Storage to allocate in GB (Default "20")
    Type: Number
    MinValue: 20
    MaxValue: 16384
    ConstraintDescription: Allocated storage size must be in range 20-16384 GB

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Database Configuration
        Parameters:
          - DatabaseInstanceType
          - DatabaseName
          - DatabaseUsername
          - DatabasePassword
    ParameterLabels:
      DatabaseName:
        default: Database name
      DatabaseInstanceType:
        default: Database Instance Type
      DatabasePassword:
        default: Database Password
      DatabaseUsername:
        default: Database Username

Resources:
  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'Kubefriendly subnet'
      DBSubnetGroupName: !Ref DatabaseName
      SubnetIds:
        - subnet-03d4e0e0a32c4c9c6
        - subnet-0d752d0329c47703b
        - subnet-0c668f116a1893dfe

  RDSCluster:
    Properties:
      DBSubnetGroupName: !Ref DBSubnetGroup
      DatabaseName:
        Ref: DatabaseName
      DBClusterParameterGroupName:
        Ref: RDSDBClusterParameterGroup
      Engine: aurora
      MasterUserPassword:
        Ref: DatabasePassword
      MasterUsername:
        Ref: DatabaseUsername
    Type: "AWS::RDS::DBCluster"

  RDSDBClusterParameterGroup:
    Properties:
      Description: "CloudFormation Sample Aurora Cluster Parameter Group"
      Family: aurora5.6
      Parameters:
        time_zone: Australia/Sydney
    Type: "AWS::RDS::DBClusterParameterGroup"

  RDSDBInstance1:
    Properties:
      AvailabilityZone: ap-southeast-2a
      DBClusterIdentifier:
        Ref: RDSCluster
      DBInstanceClass:
        Ref: DBInstanceClass
      DBParameterGroupName:
        Ref: RDSDBParameterGroup
      Engine: aurora
      PubliclyAccessible: "true"
    Type: "AWS::RDS::DBInstance"

  RDSDBInstance2:
    Properties:
      AvailabilityZone: ap-southeast-2b
      DBClusterIdentifier:
        Ref: RDSCluster
      DBInstanceClass:
        Ref: DBInstanceClass
      DBParameterGroupName:
        Ref: RDSDBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: aurora
      PubliclyAccessible: "true"
    Type: "AWS::RDS::DBInstance"

  RDSDBParameterGroup:
    Properties:
      Description: "CloudFormation Sample Aurora Parameter Group"
      Family: aurora5.6
      Parameters:
        sql_mode: IGNORE_SPACE
    Type: "AWS::RDS::DBParameterGroup"

Outputs:
  DatabaseEndpoint:
    Description: The database endpoint
    Value: !GetAtt RDSCluster.Endpoint.Address

  DatabasePort:
    Description: The database port
    Value: !GetAtt RDSCluster.Endpoint.Port